[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
console = "0.15.8"
itertools = "0.13.0"
num = "0.4.3"
regex = "1.11.1"
